# !-----------------------------------------------------------------------------------------------!
#
#    1) To hide any message, set it to [].
#    2) For UNICODE CHARACTERS (smileys, symbols, ..), save the file in UTF-8 encoding.
#
# !-----------------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------------
# This is the prefix before the messages.
# -------------------------------------------------------------------------------------------------
Prefix: "&4&lEpicChat &8// &7"

Chat:
  # -------------------------------------------------------------------------------------------------
  # Do you want to enable the chat?
  # -------------------------------------------------------------------------------------------------
  Enabled: true

  # -------------------------------------------------------------------------------------------------
  # Do you want the permission to use the chat?
  # -------------------------------------------------------------------------------------------------
  Permission_Enabled: false

  # -------------------------------------------------------------------------------------------------
  # What's the permission to use the chat?
  # -------------------------------------------------------------------------------------------------
  Permission: "chat.permission"

  # -------------------------------------------------------------------------------------------------
  # What's the permission to use a colors in the chat?
  # -------------------------------------------------------------------------------------------------
  Permission_Color: "chat.permission.color"

  # -------------------------------------------------------------------------------------------------
  # What should a chat look like?
  #
  #  1) Color codes are supported with '&' and 'ยง' symbols. Example: '&c{player_prefix}'.
  #
  #  2) Hex colors are supported with '#123456' format. Example: '#123456{player_prefix}'.
  #     This only applies for the servers 1.16 and above.
  #
  #  3) PlaceholderAPI is supported. Instead of %% use {}. Example: '{player_name}'.
  #     Placeholders: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders
  #
  #  4) Built In Placeholders:
  #     - {player_name} | Name of the player.
  #     - {message} | Message, that player sent to the chat.
  #     - {server_name} | Name of the server.
  #     - {nms_version} | Version of the server.
  #     - {timestamp} | Date and Time in format DD.MM.YYYY HH.MM.SS
  #     - {timestamp_short} | Date and Time in format DD.MM.YYYY HH.MM.
  #     - {world} | World that player is in.
  #     - {health} | Health of the player.
  #     - {location} | Location of the player.
  #     - {x} | X coordinate of the player.
  #     - {y} | Y coordinate of the player.
  #     - {z} | Z coordinate of the player.
  #     - {tab_name} | Name of the player in the tab.
  #     - {display_name} | Display name of the player.
  #     - {ip_address} | Player IP Address.
  #     - {country_code} | The code of the player country.
  #     - {country_name} | The country name of the player country.
  #     - {region_name} | The region name of the player country.
  #
  # -------------------------------------------------------------------------------------------------
  Format: "&f[&aK &7{statistic_player_kills} &cD &7%statistic_deaths%&f] {vault_prefix} &8| &f{player_name} &8>> {message}"
  Message_Color: WHITE

  Mention:
    Enabled: true
    Message: "You were mentioned by &f{0}&7."
    Color: "GREEN"
    Sound: LEVEL_UP

  Cooldown:
    Enabled: true
    Permission: "chat.cooldown.bypass"
    Message: "You can write again in {time}."
    Delay: 3

Command:
  Reload:
    # -------------------------------------------------------------------------------------------------
    # What's the permission to use the reload command?
    # -------------------------------------------------------------------------------------------------
    Permission: "chat.command.reload"

Message:
  # -------------------------------------------------------------------------------------------------
  # What's the message, when sender is console?
  # -------------------------------------------------------------------------------------------------
  No_Console: "You need to use this command in-game."

  # -------------------------------------------------------------------------------------------------
  # What's the permission message, when player don't have specific permission?
  # -------------------------------------------------------------------------------------------------
  Permission: "You don't have enough permission to use this."

  # -------------------------------------------------------------------------------------------------
  # What's the message, when plugin sub-command doesn't exist?
  # -------------------------------------------------------------------------------------------------
  Invalid_Args: "Invalid arguments. Try &f/ec &7for help."

# -------------------------------------------------------------------------------------------------
# DO NOT EDIT. Otherwise it will corrupt your plugin installation!
# -------------------------------------------------------------------------------------------------
Version: 2
