# !-----------------------------------------------------------------------------------------------!
#
#    1) To disable/hide message, set it to [] or "none".
#    2) For UNICODE CHARACTERS (smileys, symbols, ..), save the file in UTF-8 encoding.
#    3) Instead of using %% in placeholders, use {}.
#    4) You can use types in "Message" sections, see https://github.com/AdoNikeOFFICE/EpicChat/wiki/Message-Types.
#    5) Color codes are supported with '&', 'ยง', '{#hex}' or #hex (Hex colors are only supported from 1.16+ Minecraft version).
#    >  Examples: "&cHello."; "{#756D0B}Hello". For hex colors I recommend using https://htmlcolorcodes.com/.
#    6) PlaceholderAPI and Built-in placeholders are available, see https://github.com/AdoNikeOFFICE/EpicChat/wiki/Placeholders.
#
# !-----------------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------------
# This is the prefix before the messages.
# -------------------------------------------------------------------------------------------------
Prefix: "&4&lEpicChat &8//&7"

Chat:
  # -------------------------------------------------------------------------------------------------
  # Do you want to enable the chat?
  # -------------------------------------------------------------------------------------------------
  Enabled: true

  # -------------------------------------------------------------------------------------------------
  # What's the command aliases for this plugin?
  # -------------------------------------------------------------------------------------------------
  Aliases: "epicchat|chat"

  # -------------------------------------------------------------------------------------------------
  # What's the permission to use the chat?
  #
  # Set this to 'none' to disable it.
  # -------------------------------------------------------------------------------------------------
  Permission: "none"

  # -------------------------------------------------------------------------------------------------
  # What's the permission to use the colors in the chat?
  #
  # Set this to 'none' to disable it.
  # -------------------------------------------------------------------------------------------------
  Permission_Color: "epicchat.color"

  # -------------------------------------------------------------------------------------------------
  # Do you want to send the chat to the console?
  # -------------------------------------------------------------------------------------------------
  Log_Enabled: true

  # -------------------------------------------------------------------------------------------------
  # What's the default chat format?
  # -------------------------------------------------------------------------------------------------
  Format: "&f[&aK &7{statistic_player_kills} &cD &7{statistic_deaths}&f] {vault_prefix} &8| &f{player_name} &8>> {message}"

  # -------------------------------------------------------------------------------------------------
  # Color used in {message} placeholder in the "Format".
  # -------------------------------------------------------------------------------------------------
  Message_Color: "&f"

  # -------------------------------------------------------------------------------------------------
  # What's the chat format for specified group?
  #
  # For this feature Vault and Permission plugin need to be installed.
  # -------------------------------------------------------------------------------------------------
  Group_Format:
    - Name: "owner"
      Format: "&4Owner &7{player_name} &8> {message}"
      Message_Color: "&c"
    - Name: "admin"
      Format: "&2Admin &7{player_name} &8> {message}"
      Message_Color: "&a"

  # -------------------------------------------------------------------------------------------------
  # What's the shown message when player hovers on the chat format?
  #
  # Set this to "Hover: []" to disable it.
  # !! Supports only PlaceholderAPI for now (In this section: built-in placeholders not supported + use %%, instead of {}) !!
  # -------------------------------------------------------------------------------------------------
  Hover:
    - "&f%player_name%'s &7Profile"
    - " "
    - "&4| &7First Joined In &f%player_first_join_date%"
    - "&4| &7Time Played &f%statistic_time_played%"
    - "&4| &7Game Mode &f%player_gamemode%"

  Cooldown:
    # -------------------------------------------------------------------------------------------------
    # Do you want to enable Cooldown "Anti-Spam" feature?
    # -------------------------------------------------------------------------------------------------
    Enabled: true

    # -------------------------------------------------------------------------------------------------
    # What's the permission, that bypasses cooldown?
    #
    # Set this to 'none' to disable it.
    # -------------------------------------------------------------------------------------------------
    Permission: "chat.cooldown.bypass"

    # -------------------------------------------------------------------------------------------------
    # What's the message when someone spams?
    #
    # Placeholders:
    # > {time} - shows time left
    # > {time_plural} - shows time left + second/seconds
    # -------------------------------------------------------------------------------------------------
    Message: "{actionbar}You can write again in {time_plural}."

    # -------------------------------------------------------------------------------------------------
    # What's the time in seconds that player can write again?
    # -------------------------------------------------------------------------------------------------
    Delay_Seconds: 3

  Mention:
    # -------------------------------------------------------------------------------------------------
    # Do you want to enable Mention feature?
    # -------------------------------------------------------------------------------------------------
    Enabled: true

    # -------------------------------------------------------------------------------------------------
    # What's the message when player mentions someone?
    # -------------------------------------------------------------------------------------------------
    Message: "{actionbar}&7You were mentioned by &f{target_name}&7."

    # -------------------------------------------------------------------------------------------------
    # What's the color of mentioned name in the chat message?
    # -------------------------------------------------------------------------------------------------
    Color: "&a"

    # -------------------------------------------------------------------------------------------------
    # What's the sound played to the mentioned player?
    # -------------------------------------------------------------------------------------------------
    Sound: LEVEL_UP

  # -------------------------------------------------------------------------------------------------
  # You can setup own Discord bot, if you wish.
  # -------------------------------------------------------------------------------------------------
  Discord:
    # -------------------------------------------------------------------------------------------------
    # Do you want to enable Discord feature?
    # -------------------------------------------------------------------------------------------------
    Enabled: true

    # -------------------------------------------------------------------------------------------------
    # The Discord bot Token.
    # -------------------------------------------------------------------------------------------------
    Token: "BOT_TOKEN"

    # -------------------------------------------------------------------------------------------------
    # What's the ID of the Discord channel, where chat message will be sent?
    #
    # From the Discord to the Minecraft
    # &
    # From the Minecraft to the Discord
    # -------------------------------------------------------------------------------------------------
    Chat_Channel_ID: "000000000000000000"

    # -------------------------------------------------------------------------------------------------
    # What's the message sent in the Minecraft chat?
    # -------------------------------------------------------------------------------------------------
    Chat_Format: "&9&lDiscord &8| &f{member_mention} &7wrote &f{message}"

    # -------------------------------------------------------------------------------------------------
    # What's the message sent in the Discord channel?
    # -------------------------------------------------------------------------------------------------
    Discord_Format: "Minecraft | {player_name} wrote {message}"

Command:
  Reload:
    # -------------------------------------------------------------------------------------------------
    # What's the permission to use the reload command?
    #
    # Set this to 'none' to disable it.
    # -------------------------------------------------------------------------------------------------
    Permission: "chat.command.reload"

Message:
  # -------------------------------------------------------------------------------------------------
  # What's the message, when sender is console?
  # -------------------------------------------------------------------------------------------------
  No_Console: "You need to use this command in-game."

  # -------------------------------------------------------------------------------------------------
  # What's the permission message, when player don't have specific permission?
  # -------------------------------------------------------------------------------------------------
  Permission: "You don't have enough permission to use this."

  # -------------------------------------------------------------------------------------------------
  # What's the message, when plugin sub-command doesn't exist?
  # -------------------------------------------------------------------------------------------------
  Invalid_Args: "Invalid arguments. Type &f/ec &7for help."

# -------------------------------------------------------------------------------------------------
# DO NOT EDIT. Otherwise it will corrupt your plugin installation!
# -------------------------------------------------------------------------------------------------
Version: 3