# !-----------------------------------------------------------------------------------------------!
#
#    1) To hide any message, set it to [].
#    2) For UNICODE CHARACTERS (smileys, symbols, ..), save the file in UTF-8 encoding.
#
# !-----------------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------------
# This is the prefix before the messages.
# -------------------------------------------------------------------------------------------------
Prefix: "&4&lEpicChat &8// &7"

Chat:
  # -------------------------------------------------------------------------------------------------
  # Do you want to enable the chat?
  # -------------------------------------------------------------------------------------------------
  Enabled: true

  # -------------------------------------------------------------------------------------------------
  # Do you want the permission to use the chat?
  # -------------------------------------------------------------------------------------------------
  Permission_Enabled: false

  # -------------------------------------------------------------------------------------------------
  # What's the permission to use the chat?
  #
  # Only usable when 'Permission_Enabled' is enabled (true).
  # -------------------------------------------------------------------------------------------------
  Permission: "chat.permission"

  # -------------------------------------------------------------------------------------------------
  # What's the permission to use the colors in the chat?
  #
  # If player don't have this permission,
  # he can't use colors.
  # -------------------------------------------------------------------------------------------------
  Permission_Color: "chat.permission.color"

  # -------------------------------------------------------------------------------------------------
  # Do you want to send the chat to the console?
  # -------------------------------------------------------------------------------------------------
  Log_Enabled: true

  # -------------------------------------------------------------------------------------------------
  # What should a chat look like?
  #
  #  1) Color codes are supported with '&' and 'ยง' symbols. Example: '&c{player_prefix}'.
  #
  #  2) Hex colors are supported with '#123456' format. Example: '#123456{player_prefix}'.
  #     This only applies for the servers 1.16 and above.
  #
  #  3) PlaceholderAPI is supported. Instead of %% use {}. Example: '{player_name}'.
  #     Placeholders: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders
  #
  #  4) Built In Placeholders:
  #     - {player_name} | Name of the player.
  #     - {message} | Message, that player sent to the chat.
  #     - {server_name} | Name of the server.
  #     - {nms_version} | Version of the server.
  #     - {timestamp} | Date and Time in format DD.MM.YYYY HH.MM.SS
  #     - {timestamp_short} | Date and Time in format DD.MM.YYYY HH.MM.
  #     - {world} | World that player is in.
  #     - {health} | Health of the player.
  #     - {location} | Location of the player.
  #     - {x} | X coordinate of the player.
  #     - {y} | Y coordinate of the player.
  #     - {z} | Z coordinate of the player.
  #     - {tab_name} | Name of the player in the tab.
  #     - {display_name} | Display name of the player.
  #     - {ip_address} | Player IP Address.
  #     - {country_code} | The code of the player country.
  #     - {country_name} | The country name of the player country.
  #     - {region_name} | The region name of the player country.
  #
  # -------------------------------------------------------------------------------------------------
  Format: "&f[&aK &7{statistic_player_kills} &cD &7%statistic_deaths%&f] {vault_prefix} &8| &f{player_name} &8>> {message}"

  # -------------------------------------------------------------------------------------------------
  # What's the message shown, if player hover on chat format?
  # -------------------------------------------------------------------------------------------------
  Hover:
    - "ahoj"
    - "cs"

  # -------------------------------------------------------------------------------------------------
  # Default {message} color used in Format.
  # -------------------------------------------------------------------------------------------------
  Message_Color: "&f"

  Cooldown:
    # -------------------------------------------------------------------------------------------------
    # Do you want to enable Cooldown "Spam" feature?
    # -------------------------------------------------------------------------------------------------
    Enabled: true
    # -------------------------------------------------------------------------------------------------
    # What's the permission, that bypasses cooldown?
    # -------------------------------------------------------------------------------------------------
    Permission: "chat.cooldown.bypass"
    # -------------------------------------------------------------------------------------------------
    # What's the message when someone spams?
    #
    # Message Types:
    #  {actionbar}
    #  {chat}
    #  {bossbar}
    #
    # Placeholders:
    #  {time} -> shows time left
    #  {time_plural} -> shows time left + second/seconds
    # -------------------------------------------------------------------------------------------------
    Message: "{actionbar}You can write again in {time_plural}."
    # -------------------------------------------------------------------------------------------------
    # What's the time in seconds he can write again?
    # -------------------------------------------------------------------------------------------------
    Delay_Seconds: 3

  Mention:
    # -------------------------------------------------------------------------------------------------
    # Do you want to enable Mention feature?
    # -------------------------------------------------------------------------------------------------
    Enabled: true
    # -------------------------------------------------------------------------------------------------
    # What's the message when someone mentions someone?
    #
    # Message Types:
    #  {actionbar}
    #  {chat}
    #  {bossbar}
    # -------------------------------------------------------------------------------------------------
    Message: "{actionbar}You were mentioned by &f{0}&7."
    # -------------------------------------------------------------------------------------------------
    # What's the color of mentioned name in the message?
    # -------------------------------------------------------------------------------------------------
    Color: "&a"
    # -------------------------------------------------------------------------------------------------
    # What's the sound played to the mentioned player?
    # -------------------------------------------------------------------------------------------------
    Sound: LEVEL_UP

Command:
  Reload:
    # -------------------------------------------------------------------------------------------------
    # What's the permission to use the reload command?
    # -------------------------------------------------------------------------------------------------
    Permission: "chat.command.reload"

Message:
  # -------------------------------------------------------------------------------------------------
  # What's the message, when sender is console?
  # -------------------------------------------------------------------------------------------------
  No_Console: "You need to use this command in-game."

  # -------------------------------------------------------------------------------------------------
  # What's the permission message, when player don't have specific permission?
  # -------------------------------------------------------------------------------------------------
  Permission: "You don't have enough permission to use this."

  # -------------------------------------------------------------------------------------------------
  # What's the message, when plugin sub-command doesn't exist?
  # -------------------------------------------------------------------------------------------------
  Invalid_Args: "Invalid arguments. Try &f/ec &7for help."

# -------------------------------------------------------------------------------------------------
# DO NOT EDIT. Otherwise it will corrupt your plugin installation!
# -------------------------------------------------------------------------------------------------
Version: 2
